### ISSUE TITLE
What is the point of cli/resources/lang_en_data.php

### ISSUE THREAD

**Issue by mudrd8mz** [abautu/moodle-datafield_jsignature#3]
I don't get the need for it?

**Comment by abautu** [comment]
This is my first datafield plugin, so I learned from existing plugins from moodle.org. Many of them had this install hack in order to show the proper plugin name in older Moodle (I was working on 3.1 https://github.com/moodle/moodle/blob/MOODLE_31_STABLE/mod/data/lib.php#L479). 

I found a better way now (taken from Moodle 3.3 code)
